import {getTranslations} from 'next-intl/server';
import {Link} from '@/i18n/navigation';
import {formatVnd} from '@/lib/catalog';
import {getProducts} from '@/lib/catalog-server';

export default async function ProductsPage({searchParams,params}:{searchParams:Promise<{type?:string;q?:string}>;params:Promise<{locale:string}>}) {
 const [{type,q},{locale}]=await Promise.all([searchParams,params]);const t=await getTranslations('products');const catalog=await getProducts();let shown=catalog.filter(p=>!type||type==='all'||p.type===type);if(q)shown=shown.filter(p=>`${p.title} ${p.seller} ${p.category}`.toLocaleLowerCase(locale).includes(q.toLocaleLowerCase(locale)));
 return <main className="shell page-main"><span className="eyebrow">Munbase edit</span><h1 className="page-title">{t('title')}</h1><p className="muted">{t('subtitle')}</p><form className="filters" action="/products"><input className="field" name="q" defaultValue={q} placeholder="Search products" style={{maxWidth:310}}/><button className="filter" type="submit">⌕</button><Link className={`filter ${!type||type==='all'?'active':''}`} href="/products">{t('all')}</Link><Link className={`filter ${type==='physical'?'active':''}`} href="/products?type=physical">{t('physical')}</Link><Link className={`filter ${type==='digital'?'active':''}`} href="/products?type=digital">{t('digital')}</Link></form><div className="products">{shown.map(product=><Link href={`/products/${product.slug}`} className="product-card" key={product.id}><div className="product-image" style={{background:product.color,...(product.image?{backgroundImage:`url(${product.image})`,backgroundSize:'cover',backgroundPosition:'center'}:{})}}><span className="badge">{product.preview?'Preview':product.type==='digital'?t('digital'):t('physical')}</span>{!product.image&&<span className="product-mark">{product.mark}</span>}</div><div className="product-meta"><span className="product-name">{product.title}</span><span className="price">{formatVnd(product.price,locale)}</span></div><div className="shop-name">{product.seller} · ★ 4.9</div></Link>)}</div>{!shown.length&&<div className="empty">No products match this search.</div>}</main>;
}
