import 'server-only';
import {NextResponse} from 'next/server';
import {createClient} from '@supabase/supabase-js';
import {PayOS} from '@payos/node';
import {Resend} from 'resend';
import type {Webhook} from '@payos/node/lib/resources/webhooks/webhook';

export async function POST(request:Request){const {clientId,apiKey,checksumKey}=process.env;if(!clientId||!apiKey||!checksumKey)return NextResponse.json({error:'PayOS webhook is not configured.'},{status:503});const body=await request.json().catch(()=>null) as Webhook|null;if(!body)return NextResponse.json({error:'Invalid webhook body.'},{status:400});try{const payos=new PayOS({clientId,apiKey,checksumKey});const data=await payos.webhooks.verify(body);if(data.code!=='00')return NextResponse.json({success:true});const url=process.env.NEXT_PUBLIC_SUPABASE_URL;const serviceKey=process.env.SUPABASE_SERVICE_ROLE_KEY||process.env.SUPABASE_SECRET_KEY;if(!url||!serviceKey)return NextResponse.json({error:'Webhook database credentials are not configured.'},{status:503});const admin=createClient(url,serviceKey,{auth:{persistSession:false,autoRefreshToken:false}});const {data:previous}=await admin.from('orders').select('id,payment_status,customer_email,customer_name').eq('order_code',data.orderCode).maybeSingle();const {error}=await admin.rpc('confirm_payos_payment',{p_order_code:data.orderCode,p_amount:data.amount,p_event_id:data.reference,p_payload:body});if(error)return NextResponse.json({error:'Payment event did not match an order.'},{status:400});if(previous?.payment_status!=='paid'&&previous?.customer_email&&process.env.RESEND_API_KEY&&process.env.RESEND_FROM_EMAIL){const base=process.env.NEXT_PUBLIC_SITE_URL||new URL(request.url).origin;const resend=new Resend(process.env.RESEND_API_KEY);await resend.emails.send({from:process.env.RESEND_FROM_EMAIL,to:previous.customer_email,subject:`Munbase order ${data.orderCode} confirmed`,html:`<p>Hello ${escapeHtml(previous.customer_name)},</p><p>Your payment has been confirmed. View your order and any digital downloads here:</p><p><a href="${base}/vi/orders/${previous.id}">View order ${data.orderCode}</a></p>`}).catch(()=>undefined);}return NextResponse.json({success:true});}catch{return NextResponse.json({error:'PayOS signature verification failed.'},{status:400});}}

function escapeHtml(value:string){return value.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');}
