'use client';
import {useState} from 'react';
import {useRouter} from '@/i18n/navigation';
import {useTranslations} from 'next-intl';
import {createSupabaseBrowserClient} from '@/lib/supabase/browser';
type Item={product_id:string;product_title:string;quantity:number;unit_price:number;product_type:string};
type Shipment={id:string;status:string;carrier:string|null;tracking_number:string|null};
export function AdminOrderTools({orderId,address,phone,items,shipment,paymentMethod,paymentStatus}:{orderId:string;address:unknown;phone:string|null;items:Item[];shipment:Shipment|null;paymentMethod:string;paymentStatus:string}){const t=useTranslations('adminOrders');const router=useRouter();const [reason,setReason]=useState('');const [addr,setAddr]=useState(JSON.stringify(address??{},null,2));const [tel,setTel]=useState(phone||'');const [quantities,setQuantities]=useState(items.map(i=>i.quantity));const [amount,setAmount]=useState('');const [evidence,setEvidence]=useState('');const [carrier,setCarrier]=useState(shipment?.carrier||'');const [tracking,setTracking]=useState(shipment?.tracking_number||'');const [status,setStatus]=useState(shipment?.status||'pending');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);
async function invoke(name:string,args:Record<string,unknown>,success:string){if(reason.trim().length<3){setMessage(t('reasonRequired'));return;}const supabase=createSupabaseBrowserClient();if(!supabase){setMessage(t('notConfigured'));return;}setBusy(true);const {error}=await supabase.rpc(name,args as never);setMessage(error?error.message:success);if(!error)router.refresh();setBusy(false);}
const payload=items.filter((_,i)=>quantities[i]>0).map(item=>({productId:item.product_id,quantity:quantities[items.indexOf(item)]}));
function saveAddress(){let parsed:unknown;try{parsed=JSON.parse(addr);}catch{setMessage(t('invalidAddress'));return;}void invoke('admin_update_order_shipping',{p_order_id:orderId,p_address:parsed,p_phone:tel,p_reason:reason},t('addressSaved'));}
function adjustItems(){void invoke(paymentMethod==='cod'?'admin_adjust_pending_cod_order':'admin_reissue_pending_sepay_order',{p_order_id:orderId,p_items:payload,p_reason:reason},t(paymentMethod==='cod'?'adjusted':'reissueSuccess'));}
function cancel(){if(!window.confirm(t('cancelConfirm')))return;void invoke('admin_cancel_unpaid_order',{p_order_id:orderId,p_reason:reason},t('cancelledSuccess'));}
function saveShipment(){if(!shipment){setMessage(t('noShipment'));return;}void invoke('admin_set_shipment_status',{p_shipment_id:shipment.id,p_status:status,p_carrier:carrier,p_tracking:tracking,p_reason:reason},t('shipmentSaved'));}
async function createAdjustment(){const delta=Number(amount);if(!Number.isSafeInteger(delta)||delta===0){setMessage(t('invalidAmount'));return;}const supabase=createSupabaseBrowserClient();if(!supabase){setMessage(t('notConfigured'));return;}if(reason.trim().length<3){setMessage(t('reasonRequired'));return;}setBusy(true);const {error}=await supabase.rpc('admin_create_financial_adjustment',{p_order_id:orderId,p_delta_amount:delta,p_reason:reason,p_evidence_reference:evidence,p_request_key:crypto.randomUUID()});setMessage(error?error.message:t('adjustmentCreated'));if(!error){setAmount('');router.refresh();}setBusy(false);}
return <section className="admin-order-tools card-panel form-grid"><label>{t('reason')}<textarea className="field" minLength={3} maxLength={2000} value={reason} onChange={e=>setReason(e.target.value)}/></label><section><h2>{t('address')}</h2><label>{t('addressJson')}<textarea className="field" rows={5} value={addr} onChange={e=>setAddr(e.target.value)}/></label><label>{t('phone')}<input className="field" value={tel} onChange={e=>setTel(e.target.value)}/></label><button className="button secondary" disabled={busy} onClick={saveAddress}>{t('saveAddress')}</button></section>{paymentStatus==='pending'&&<section><h2>{t('items')}</h2>{items.map((item,i)=><label key={item.product_id}>{item.product_title} · {item.product_type} · {item.unit_price.toLocaleString()} VND<input aria-label={item.product_title} className="field" type="number" min={0} max={99} value={quantities[i]} onChange={e=>setQuantities(q=>q.map((v,n)=>n===i?Number(e.target.value):v))}/></label>)}<button className="button secondary" disabled={busy} onClick={adjustItems}>{t(paymentMethod==='cod'?'adjustCod':'reissueSepay')}</button>{paymentMethod==='sepay'&&<p className="muted">{t('replaceWarning')}</p>}</section>}{paymentStatus==='pending'&&<button className="button danger" disabled={busy} onClick={cancel}>{t('cancelOrder')}</button>}{shipment&&<section><h2>{t('shipment')}</h2><label>{t('shipmentStatus')}<select className="field" value={status} onChange={e=>setStatus(e.target.value)}>{['pending','ready_to_ship','shipped','delivered','cancelled'].map(s=><option value={s} key={s}>{s}</option>)}</select></label><label>{t('carrier')}<input className="field" value={carrier} onChange={e=>setCarrier(e.target.value)}/></label><label>{t('tracking')}<input className="field" value={tracking} onChange={e=>setTracking(e.target.value)}/></label><button className="button secondary" disabled={busy} onClick={saveShipment}>{t('saveShipment')}</button></section>}{(paymentStatus==='paid'||shipment?.status==='delivered')&&<section><h2>{t('financialAdjustment')}</h2><p className="muted">{t('adjustmentLedgerHint')}</p><label>{t('deltaAmount')}<input className="field" type="number" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label>{t('evidence')}<input className="field" value={evidence} onChange={e=>setEvidence(e.target.value)}/></label><button className="button secondary" disabled={busy} onClick={()=>void createAdjustment()}>{t('createAdjustment')}</button></section>}{message&&<p role="status" className="muted">{message}</p>}</section>}
export function SettleAdjustment({id}:{id:string}){const t=useTranslations('adminOrders');const router=useRouter();const [reference,setReference]=useState('');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);async function settle(){if(reference.trim().length<3){setMessage(t('referenceRequired'));return;}const supabase=createSupabaseBrowserClient();if(!supabase){setMessage(t('notConfigured'));return;}setBusy(true);const {error}=await supabase.rpc('admin_settle_order_adjustment',{p_adjustment_id:id,p_reference:reference});setMessage(error?error.message:t('settled'));if(!error)router.refresh();setBusy(false);}return <div className="inline-form"><input className="field" aria-label={t('reference')} placeholder={t('reference')} value={reference} onChange={e=>setReference(e.target.value)}/><button className="button secondary" disabled={busy} onClick={()=>void settle()}>{t('settle')}</button>{message&&<span role="status">{message}</span>}</div>}
