'use client';
import {useEffect,useRef,useState} from 'react';
import {useTranslations} from 'next-intl';
import {useTheme} from 'next-themes';
import {Menu,Moon,ShoppingBag,Sun,X} from 'lucide-react';
import {usePathname,useRouter,Link} from '@/i18n/navigation';
import {createSupabaseBrowserClient} from '@/lib/supabase/browser';

export function SiteHeader({locale}:{locale:string}){
  const t=useTranslations('nav');const {resolvedTheme,setTheme}=useTheme();const pathname=usePathname();const router=useRouter();const [count,setCount]=useState(0);const [signedIn,setSignedIn]=useState(false);const [isAdmin,setIsAdmin]=useState(false);const [menuOpen,setMenuOpen]=useState(false);const menuButton=useRef<HTMLButtonElement>(null);
  useEffect(()=>{if(!menuOpen)return;const onKeyDown=(event:KeyboardEvent)=>{if(event.key==='Escape'){setMenuOpen(false);menuButton.current?.focus();}};window.addEventListener('keydown',onKeyDown);return()=>window.removeEventListener('keydown',onKeyDown);},[menuOpen]);
  useEffect(()=>{const read=()=>{try{const c=JSON.parse(localStorage.getItem('munbase-cart')||'[]') as {quantity:number}[];setCount(c.reduce((n,x)=>n+x.quantity,0));}catch{setCount(0);}};read();window.addEventListener('storage',read);window.addEventListener('munbase-cart-change',read);return()=>{window.removeEventListener('storage',read);window.removeEventListener('munbase-cart-change',read);};},[]);
  useEffect(()=>{const supabase=createSupabaseBrowserClient();if(!supabase)return;let active=true;const sync=async(userId:string|null)=>{setSignedIn(Boolean(userId));setIsAdmin(false);if(!userId)return;const {data}=await supabase.from('profiles').select('theme_preference,role').eq('id',userId).maybeSingle();if(active&&data?.theme_preference)setTheme(data.theme_preference);if(active)setIsAdmin(data?.role==='admin');};void supabase.auth.getUser().then(({data})=>sync(data.user?.id||null));const {data:{subscription}}=supabase.auth.onAuthStateChange((_event,session)=>{void sync(session?.user.id||null);});return()=>{active=false;subscription.unsubscribe();};},[setTheme]);
  async function signOut(){const supabase=createSupabaseBrowserClient();if(supabase)await supabase.auth.signOut();setSignedIn(false);router.push('/');router.refresh();}
  async function toggleTheme(){const next=resolvedTheme==='dark'?'light':'dark';setTheme(next);const supabase=createSupabaseBrowserClient();if(!supabase)return;const {data:{user}}=await supabase.auth.getUser();if(user)await supabase.from('profiles').update({theme_preference:next}).eq('id',user.id);}
  return <header className="shell header"><Link className="brand" href="/">mun<span>base</span></Link><nav aria-label={t('navigation')} style={{display:'flex',alignItems:'center',gap:22}}><Link className="nav-link nav-explore" href="/products">{t('explore')}</Link><Link className="nav-link nav-seller" href="/dashboard">{t('seller')}</Link>{signedIn?<><Link className="nav-link nav-account" href="/account">{t('account')}</Link>{isAdmin&&<Link className="nav-link nav-admin" href="/admin">{t('admin')}</Link>}<button className="nav-link nav-signout" onClick={signOut} style={{background:'none',border:0,cursor:'pointer'}}>{t('signOut')}</button></>:<Link className="nav-link nav-login" href="/login">{t('login')}</Link>}<Link aria-label={`${t('cart')} (${count})`} href="/cart" style={{display:'flex',alignItems:'center',gap:4}}><ShoppingBag size={18}/><small>{count}</small></Link><select aria-label="Language" className="field" style={{width:70,padding:'6px 4px'}} value={locale} onChange={e=>router.replace(pathname,{locale:e.target.value as 'vi'|'en'|'ko'|'zh'|'ja'})}><option value="vi">VI</option><option value="en">EN</option><option value="ko">KO</option><option value="zh">ZH</option><option value="ja">JA</option></select><button aria-label="Toggle color theme" onClick={()=>void toggleTheme()} style={{background:'none',border:0,color:'var(--ink)',cursor:'pointer'}}><Sun className="theme-light-icon" size={18}/><Moon className="theme-dark-icon" size={18}/></button><button ref={menuButton} className="mobile-menu-button" type="button" aria-label={menuOpen?t('closeMenu'):t('openMenu')} aria-expanded={menuOpen} aria-controls="mobile-navigation" onClick={()=>setMenuOpen(!menuOpen)}>{menuOpen?<X size={19}/>:<Menu size={19}/>}</button></nav>{menuOpen&&<nav id="mobile-navigation" className="mobile-nav-panel" aria-label={t('navigation')} onClick={()=>setMenuOpen(false)}><Link href="/products">{t('explore')}</Link><Link href="/dashboard">{t('seller')}</Link>{signedIn?<><Link href="/account">{t('account')}</Link>{isAdmin&&<Link href="/admin">{t('admin')}</Link>}<button onClick={signOut}>{t('signOut')}</button></>:<Link href="/login">{t('login')}</Link>}<Link href="/cart">{t('cart')} · {count}</Link></nav>}</header>;
}
