import {getTranslations} from 'next-intl/server';
import {ArrowUpRight, ArrowRight} from 'lucide-react';
import {Link} from '@/i18n/navigation';
import {formatVnd} from '@/lib/catalog';
import {getProducts} from '@/lib/catalog-server';

export default async function Home({params}:{params:Promise<{locale:string}>}) {
  const {locale}=await params; const t=await getTranslations('home'); const nav=await getTranslations('nav'); const catalog=await getProducts();
  return <main className="shell"><section className="hero"><div><span className="eyebrow">{t('eyebrow')}</span><h1>{t('title')}</h1><p>{t('description')}</p><div className="hero-actions"><Link className="button" href="/products">{t('explore')} <ArrowUpRight size={16}/></Link><Link className="button secondary" href="/dashboard">{t('seller')}</Link></div></div><div className="hero-art" role="img" aria-label="An abstract illustration inspired by a Vietnamese market"><span className="art-tag">Những điều nhỏ, niềm vui lớn</span></div></section>
    <section className="section"><div className="section-head"><div><span className="eyebrow">Munbase edit</span><h2>{t('categories')}</h2></div><Link className="nav-link" href="/products">{t('viewAll')} <ArrowRight size={14}/></Link></div><div className="categories">{[['✳','Đặc sản'],['◒','Thủ công'],['⌘','Sáng tạo số'],['⌂','Đời sống']].map(([icon,name])=><Link href="/products" className="category" key={name}><span className="category-icon">{icon}</span><strong>{name}</strong></Link>)}</div></section>
    <section className="section"><div className="section-head"><div><span className="eyebrow">Curated by Munbase</span><h2>{t('featured')}</h2></div><Link className="nav-link" href="/products">{t('viewAll')} <ArrowRight size={14}/></Link></div>{catalog.length?<div className="products">{catalog.slice(0,4).map(product=><Link href={`/products/${product.slug}`} className="product-card" key={product.id}><div className="product-image" style={{background:product.color,...(product.image?{backgroundImage:`url(${product.image})`,backgroundSize:'cover',backgroundPosition:'center'}:{})}}><span className="badge">{product.preview?'Preview':product.type==='digital'?t('digital'):t('physical')}</span>{!product.image&&<span className="product-mark">{product.mark}</span>}</div><div className="product-meta"><span className="product-name">{product.title}</span><span className="price">{formatVnd(product.price,locale)}</span></div><div className="shop-name">{product.seller}</div></Link>)}</div>:<div className="empty">New products are on their way.</div>}</section>
    <section className="section"><div className="promise"><div><span className="eyebrow">{nav('seller')}</span><h2>{t('promise')}</h2></div><div><p>{t('promiseText')}</p><Link className="button" href="/dashboard">{t('seller')} <ArrowUpRight size={16}/></Link></div></div></section>
  </main>;
}
