import {getTranslations} from 'next-intl/server';
import {ArrowUpRight, ArrowRight, Boxes, Coffee, Heart, Sparkles} from 'lucide-react';
import {Link} from '@/i18n/navigation';
import {formatVnd} from '@/lib/catalog';
import {getProducts} from '@/lib/catalog-server';

export default async function Home({params}:{params:Promise<{locale:string}>}) {
  const {locale}=await params; const t=await getTranslations('home'); const nav=await getTranslations('nav'); const catalog=await getProducts(locale);
  return <main className="shell"><section className="hero"><div><span className="eyebrow">{t('eyebrow')}</span><h1>{t('title')}</h1><p>{t('description')}</p><div className="hero-actions"><Link className="button" href="/products">{t('explore')} <ArrowUpRight size={16}/></Link><Link className="button secondary" href="/dashboard">{t('seller')}</Link></div></div><div className="hero-art" aria-hidden="true"><span className="art-tag">{t('heroTag')}</span></div></section>
    <section className="section"><div className="section-head"><div><span className="eyebrow">Munbase edit</span><h2>{t('categories')}</h2></div><Link className="nav-link" href="/products">{t('viewAll')} <ArrowRight size={14}/></Link></div><div className="categories">{[[Coffee,'categoryFood'],[Heart,'categoryCraft'],[Sparkles,'categoryDigital'],[Boxes,'categoryLiving']].map(([Icon,key])=>{const C=Icon as typeof Coffee;const k=key as string;return <Link href="/products" className="category" key={k}><C className="category-icon" size={23}/><strong>{t(k)}</strong></Link>;})}</div></section>
    <section className="section"><div className="section-head"><div><span className="eyebrow">Curated by Munbase</span><h2>{t('featured')}</h2></div><Link className="nav-link" href="/products">{t('viewAll')} <ArrowRight size={14}/></Link></div>{catalog.length?<div className="products">{catalog.slice(0,4).map(product=><Link href={`/products/${product.slug}`} className="product-card" key={product.id}><div className="product-image" style={{background:product.color,...(product.image?{backgroundImage:`url(${product.image})`,backgroundSize:'cover',backgroundPosition:'center'}:{})}}><span className="badge">{product.type==='digital'?t('digital'):t('physical')}</span>{!product.image&&<span className="product-mark">{product.mark}</span>}</div><div className="product-meta"><span className="product-name">{product.title}</span><span className="price">{formatVnd(product.price,locale)}</span></div><div className="shop-name">{product.seller}</div></Link>)}</div>:<div className="empty">{t('empty')}</div>}</section>
    <section className="section"><div className="promise"><div><span className="eyebrow">{nav('seller')}</span><h2>{t('promise')}</h2></div><div><p>{t('promiseText')}</p><Link className="button" href="/dashboard">{t('seller')} <ArrowUpRight size={16}/></Link></div></div></section>
  </main>;
}
